spring:
  datasource:
    username: root
    password: Zy10300936
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1u2h6esm9zyp3y5ho.mysql.rds.aliyuncs.com:3306/blog
#    url: jdbc:mysql://rm-bp1u2h6esm9zyp3y5.mysql.rds.aliyuncs.com:3306/blog
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
  devtools:
    remote:
      restart:
        enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
server:
  ssl:
    key-store: classpath:shangxirui.pfx
    key-store-password: 38F38rmB
    key-store-type: PKCS12
  servlet:
    session:
      timeout: 60m

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4FrfHREKsVsnPKqqsuDs
  accessKeySecret: Oxfj5t0bTIMmCUA07ZyLuZ4AlW48yo
  bucketName: zy-blog
